"""empty message

Revision ID: f29c8a8dba1b
Revises: 
Create Date: 2026-02-05 17:03:09.759569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29c8a8dba1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(length=100), nullable=False),
    sa.Column('client', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('paid_date', sa.DateTime(), nullable=True),
    sa.Column('photo_path', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shields_date_created'), ['date_created'], unique=False)
        batch_op.create_index(batch_op.f('ix_shields_paid_date'), ['paid_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shields_paid_date'))
        batch_op.drop_index(batch_op.f('ix_shields_date_created'))

    op.drop_table('shields')
    # ### end Alembic commands ###
